control_freq_factor: 5

# Topic Names
imu_topic: "/hummingbird/ground_truth/imu"
motor_thrust_topic: "/hummingbird/command/ros_gp_mpc/motor_thrust"
record_topic: "/hummingbird/record_mhe"

# Simulate Sensor Noise Levels
sensor_noise: false
# # Noise Level I ------------------
# p_noise_std: 0.007
# r_noise_std: 0.007
# a_noise_std: 0.007
# # Noise Level II -----------------
# p_noise_std: 0.5
# r_noise_std: 0.015
# a_noise_std: 0.01
# # Noise Level III ----------------
p_noise_std: 1
r_noise_std: 0.03
a_noise_std: 0.1