# Parameters for the loop and lemniscate trajectories at successively increasing speed
loop_z: 1.05             # Z position of loop plane [m]
z_dim: 0.0             # Change in Z position of loop plane [m]
loop_r: 3.0            # Radius of loop [m]
loop_v_max: 3.0       # Maximum speed achieved (approx.) [m/s]  1.94
loop_lin_a: 0.25       # Linear acceleration and deceleration of trajectory [m/s^2]
loop_clockwise: False  # Rotation direction of the quad
loop_yawing: False     # Yaw quadrotor along the circle (only for loop)
world_limits: 'arena_limits' 